name: Build

on:
  pull_request:
    branches:
      - '*'
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 10 # this might cause issues if there are more than 10 commits in a PR (?)
      - uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc
      - name: Install pnpm
        run: npm install -g pnpm@9
      - name: Set pnpm store directory
        run: echo "PNPM_STORE_PATH=$(pnpm store path)" >> $GITHUB_ENV
      - name: Set up pnpm cache
        uses: actions/cache@v4
        with:
          path: ${{ env.PNPM_STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: ${{ runner.os }}-pnpm-store-
      - name: Install JavaScript packages
        run: pnpm install --frozen-lockfile
      - name: Run Prettier
        run: ./node_modules/.bin/prettier --check
      - name: Run ESLint
        run: ./node_modules/.bin/eslint --max-warnings 0 .
      - name: Run web-ext
        run: ./bin/lint/web-ext
